---
version: 2
jobs:
  build:
    docker:
      - image: node:10-alpine
    steps:
      - checkout
      - run:
          name: NPM Install & Lerna Bootstrap
          command: npm install --unsafe-perm
